variable "env" {}
variable "service" {}
variable "vpc_id" {}
variable "tags" {}
variable "app_port" {}
variable "sg_ingress_cidr_blocks" {}
variable "default_vpc_cidr_block" {}
variable "health_check_path" {}
variable "default_vpc_id" {}
variable "az" {}
variable "hosted_zone_id" {}
variable "public_lb_dns_name" {}
variable "private_lb_dns_name" {}
variable "private_lb_listener_arn" {}
variable "lb_priority" {}
variable "public_alb_listener_arn" {}
variable "instance_type" {}
variable "app_subnet_ids" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "ami_id" {}
variable "key_name" {}